server:
  port : 80
  error:
    include-message: always
    whitelabel:
      enabled: false
redis:
  host: localhost
  port: 6379
spring:
  application:
    name: unit-test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
unittest:
  config:
    retry:
      login: 3
  session:
    expired:
      signing: 600
      cooldown: 86400 #1 hari untuk expired
      catalog : 3600
  esb:
    masterData:
      catalog:
        url: http://60a395d47c6e8b0017e2751c.mockapi.io/api/v1/catalog
swagger:
  host: "localhost:80"