server:
  port : 8090
  error:
    include-message: always
    whitelabel:
      enabled: false
redis:
  host: redis-13426.c262.us-east-1-3.ec2.cloud.redislabs.com
  port: 13426
  username: default
  password: GgtOND4d4vgaS64l7Ovu7L4coQXFJ5vZ
spring:
  application:
    name: unit-test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-44-206-197-71.compute-1.amazonaws.com:5432/ddtbq5hm8r561f?user=plfjnhkazkspyp&password=7e1e2a05b3a3648cff4243f95988dce85789b69734dfd138633189d29573034e
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
unittest:
  config:
    retry:
      login: 3
  session:
    expired:
      signing: 600
      cooldown: 86400 #1 day
      catalog : 3600
  esb:
    masterData:
      catalog:
        url: http://60a395d47c6e8b0017e2751c.mockapi.io/api/v1/catalog
swagger:
  host: "localhost:80"